proxies:
  - name: "IT1"
    type: vless
    server: 104.25.150.137
    port: 443
    uuid: b32d498e-bbac-4f5f-92bb-ea49d5d6ee94
    network: ws
    tls: true
    udp: true
    servername: ez-2f4a7e.ezaccess15c2114.workers.dev
    client-fingerprint: chrome
    ws-opts:
      path: /
      headers:
        Host: ez-2f4a7e.ezaccess15c2114.workers.dev

  - name: "IT2"
    type: vless
    server: 172.67.74.146
    port: 80
    uuid: f153bc6f-429b-2dba-3c02-c7a32c18c84f
    network: ws
    tls: false
    udp: true
    ws-opts:
      path: /mohsen
      headers:
        Host: late-meadow-9336.mohsen-net.workers.dev

  - name: "DE1"
    type: vless
    server: 172.67.193.253
    port: 443
    uuid: 4f013568-a58b-4b04-b5dd-4d52bf1c33a4
    network: ws
    tls: true
    udp: true
    servername: amoosamiii.net
    client-fingerprint: chrome
    ws-opts:
      path: /poiuyws
      headers:
        Host: amoosamiii.net

  - name: "IT3"
    type: vless
    server: 104.17.122.42
    port: 80
    uuid: 7b45b4db-4b7a-4e47-b02a-f422d88add60
    network: ws
    tls: false
    udp: true
    ws-opts:
      path: /In_Panel_Rayeghan_Ast_Va_Gheyre_Ghabele_Foroosh
      headers:
        Host: zeus-panel-yikvzz.saman-co-com1385.workers.dev

  - name: "DE2"
    type: vless
    server: 104.17.69.151
    port: 443
    uuid: 4f013568-a58b-4b04-b5dd-4d52bf1c33a4
    network: ws
    tls: true
    udp: true
    servername: amoosamiii.net
    client-fingerprint: chrome
    ws-opts:
      path: /poiuyws
      headers:
        Host: amoosamiii.net

  - name: "IT4"
    type: trojan
    server: assets.fiverr.com
    port: 443
    password: MITIVPN
    network: ws
    udp: true
    sni: us-a.App-Cloud.ir
    client-fingerprint: chrome
    ws-opts:
      path: /MiTiVPN=USA

  - name: "DE3"
    type: vless
    server: 172.67.74.2
    port: 443
    uuid: 7e544a9d-7667-413b-bbb0-b3bb1aac6d77
    network: ws
    tls: true
    udp: true
    servername: shegeftihaaa.net
    client-fingerprint: chrome
    ws-opts:
      path: /rsedgws
      headers:
        Host: shegeftihaaa.net

  - name: "IT5"
    type: trojan
    server: assets.fiverr.com
    port: 443
    password: MITIVPN
    network: ws
    udp: true
    sni: Ger.App-Cloud.ir
    client-fingerprint: chrome
    ws-opts:
      path: /MiTiVPN=DE

  - name: "IT6"
    type: vless
    server: 104.26.10.5
    port: 443
    uuid: 5a87479f-05d0-6033-3def-6e1e00000000
    network: ws
    tls: true
    udp: true
    servername: wisp.nova-d5364c.workers.dev
    client-fingerprint: chrome
    ws-opts:
      path: /sync
      headers:
        Host: wisp.nova-d5364c.workers.dev

  - name: "IT7"
    type: trojan
    server: www.speedtest.net
    port: 443
    password: MiTiVPN
    network: ws
    udp: true
    sni: sw-W.App-Cloud.ir
    client-fingerprint: chrome
    ws-opts:
      path: /MiTiVPN=Sw

  - name: "IT8"
    type: trojan
    server: assets.fiverr.com
    port: 443
    password: MiTiVPN
    network: ws
    udp: true
    sni: Nl-L.App-Cloud.ir
    client-fingerprint: chrome
    ws-opts:
      path: /MiTiVPN=N-L

  - name: "DE4"
    type: vless
    server: 173.245.59.162
    port: 443
    uuid: c35050ce-01ab-45a9-91b8-54cec637d0a8
    network: ws
    tls: true
    udp: true
    servername: octopusss5.info
    client-fingerprint: chrome
    ws-opts:
      path: /udfyfws
      headers:
        Host: octopusss5.info

  - name: "DE5"
    type: vless
    server: octopusss5.info
    port: 443
    uuid: c35050ce-01ab-45a9-91b8-54cec637d0a8
    network: ws
    tls: true
    udp: true
    servername: octopusss5.info
    client-fingerprint: chrome
    ws-opts:
      path: /udfyfws
      headers:
        Host: octopusss5.info

proxy-groups:
  - name: "Select"
    type: select
    proxies:
      - IT1
      - IT2
      - DE1
      - IT3
      - DE2
      - IT4
      - DE3
      - IT5
      - IT6
      - IT7
      - IT8
      - DE4
      - DE5

rules:
  - MATCH,Select
